maxlath/wikibase-sdk

README.md
Just a small fix for the readme documentation for parsing wdq responses.
=> Fixed outdated readme for parsing wdq responses

src/queries/wikidata_search_entities.coffee
The example given in readme doesn't work, this should fix it.
Url generated : https://www.wikidata.org/w/api.php?action=wbsearchentities&search=Ingmar%20Bergman&language=fr&limit=10&format=20
Error returned :
```
"error": {
"code": "unknown_format",
"info": "Unrecognized value for parameter 'format': 20",
"*": "See https://www.wikidata.org/w/api.php for API usage"
}
```
=> fix: search_entities default "format" value is invalid

docs/simplify_claims.md, lib/helpers/simplify_claims.js, test/simplify_claims.js
I think that providing the value type on rich value claims could be beneficial.
For example:
```js
const simplifiedClaims = wdk.simplify.claims(entity.claims, { keepType: true });
```
```
"P279": [ { "type": "wikibase-entityid", "value": "Q340169" } ]
```
=> Add support for `keepTypes` on simplify.claims

docs/get_entities.md
It seems there is an error in the documentation about getManyEntities.
If this was intentional feel free to close this PR.
=> Fix getManyEntities example in get_entities.md

lib/helpers/helpers.js
Numeric values of entity ids never start with `0` so more false positives can be eleminated.
=> Extend entity id checks

lib/helpers/helpers.js, lib/helpers/wikidata_time_to_date_object.js, test/helpers.js
Follow up to #51: years with more than 6 digits currently have a related bug because they fall back to `bestEffort`, which only handles the case where _both_ month and day are `00`, but not day only. Not that I would expect to see many time values that far in the past/future with month precision, but hey...
Secondly, dates with positive years from 5-6 digits currently fall back to `bestEffort` because they fail parsing, but they should pass. They just need to be padded and signed similar to negative years.
This PR fixes those edge cases, and there are also a couple more tests to cover e8edbdd5b2a00c6ec33c3ffda5179b14d352180b
=> Fix more time converter helper edge cases

.gitignore, package.json, tsconfig.json, types/claim.d.ts, types/entity.d.ts, types/helper.d.ts, types/index.d.ts, types/options.d.ts, types/search.d.ts, types/sparql.d.ts, types/test/README.md, types/test/main.ts, types/test/simplify-qualifier.ts
This adds TypeScript types for the library. Even when not using TypeScript itself many IDEs read TypeScript type definitions in order to provide better autocompletion.
Is this something you would like to add?
I migrated two projects of mine to typescript while using this typedefs and had no problem yet.
Currently it is not complete, some simplify methods are missing.
I can add them when you think TypeScript type definitions are a great benefit for this project.
~Also please check out https://github.com/maxlath/wikidata-sdk/commit/a8b0dd4ea842f7a7f336538508a9b47a05be09f6 as that is unrelated to typescript itself but fixes problems for me to work with this library. Is there something I am not seeing or is jsondepth simply not needed (anymore)?~
=> Typescript

docs/simplify_claims.md, lib/helpers/parse_claim.js, test/simplify_claims.js, test/simplify_qualifiers.js
This allows to pass a custom function for the timeConverter option.
=> feat(simplify_claims): timeConverter as function

docs/sparql_query.md
The example code does not wrok without adding a user agent in the header of the request.
=> added information on the required user agent

src/helpers/special_sites.ts
This will add the correct type to Site which was previously just string.
Before:
After:
=> Add "as const" to specialSites

package.json
Currently the exports dont know they have typings
=> build(npm): set types for exports

.eslintrc.cjs, package-lock.json, package.json, src/helpers/helpers.ts, src/helpers/simplify_text_attributes.ts, tests/simplify_qualifiers.ts
Some lints have an improved version for TypeScript. I disabled the JS ones and used the ones for TypeScript.
As the `eslint-config-standard` is used there is no need for the devDependency `eslint-plugin-standard`.
=> refactor: use typescript lints over javascript lints

README.md
Use shields which automatically load info from NPM like version, required Node.js version, license, … instead of custom tests.
Also add one for the type definitions and added a shield for the download stats link.
I removed the larger upper one as it doesnt show anything else then `npm install wikibase-sdk` (despite the url parameters containing starts and so on) as other shields already contain info like download stats.
=> docs(readme): improve shields

src/helpers/parse_responses.ts, src/helpers/simplify.ts, src/helpers/simplify_entity.ts, src/index.ts, src/wellknown/wikidata.org.ts, src/wikibase-sdk.ts, tests/general.ts, tests/parse.ts
the Wbk interface has a lot of duplicate types which result in easy errors.
This removes a lot of these duplicates and the exact types of the functions are used.
Minor downside: types like `type Url = string` get simplified sometimes by TypeScript and look like string afterwards.
This should not breaking as long as no one used simplify or parse as an object (why should someone do that) (look at the tests/general to see what I mean).
very likely conflicts with #100 but this can easily be extended as #100 would only be the change in index.ts with this Pull Request.
=> refactor: improve Wdk export

package-lock.json, package.json, tests/lib/utils.ts, tsconfig.json
The `@types/node` package introduced some types which don't work in Node.js 12. Using the same version as the minimum required Node.js version changes this.
`Object.fromEntries` is ES2019 which is higher than the current target of ES2016. I used an implementation which works with ES2016.
According to [this config](https://github.com/tsconfig/bases/blob/main/bases/node12.json) Node.js 12 supports ES2019 so the alternative might be to raise the target. Browsers basically seem to [support it after 2019](https://caniuse.com/sr_es10).
=> Reduce allowed types

src/helpers/rank.ts, src/helpers/simplify_text_attributes.ts, src/helpers/sitelinks.ts, src/queries/cirrus_search.ts, src/utils/utils.ts
Adds two type safe utils to work with JS builtins in a more type safe way.
Also prefer using `Object.entries` (or `typedEntries`) over `Object.keys(obj)` with manual access of the value `obj[key]` as indexed access could return undefined and TypeScript knows that (with noUncheckedIndexedAccess). Using entries there will contain the value so no need for another check.
(Part of #106)
=> refactor: use typesave utils

src/helpers/simplify_sparql_results.ts, src/types/sparql.ts
Basically adding types to the internals which found a bug: standaloneVars were able to have a null value. This is fixed by a null check.
=> fix(sparql): types and possible null in output

src/index.ts, src/types/claim.ts, src/types/snakvalue.ts, tests/time.ts
also some minor Claim/Snak typing improvements.
SnakValue typings should be complete based on what I found [here](https://www.mediawiki.org/wiki/Wikibase/Indexing/RDF_Dump_Format#Value_representation).
Something I am not sure about: no `Snak` (`Qualifier` and `ReferenceSnak` included) contains an id (from the real world data I observed.
its optional for Snak but required for ReferenceSnak and Qualifier. I think this is wrong and can be remove on all 3 of them. But I might be missing something so can someone confirm me here? Its there so it probably has a reason?
=> fix(claim): improve SnakValue type

src/helpers/helpers.ts, src/helpers/sitelinks.ts, src/queries/cirrus_search.ts, src/queries/get_entities.ts, src/queries/get_entities_from_sitelinks.ts, src/queries/get_entity_revision.ts, src/queries/get_many_entities.ts, src/queries/get_reverse_claims.ts, src/queries/get_revisions.ts, src/queries/search_entities.ts, src/queries/sparql_query.ts, src/types/options.ts, src/types/sitelinks.ts, src/utils/build_url.ts, src/wikibase-sdk.ts, tests/lib/utils.ts
Improved typings of the BuildUrlFunction and
move the Url type to the build_url file
part of #106
=> refactor: improve build_url

docs/simplify_claims.md, scripts/compare_datatypes.ts, src/helpers/parse_snak.ts, src/helpers/simplify.ts, src/helpers/simplify_claims.ts, src/types/claim.ts, src/types/options.ts, src/types/simplify_claims.ts, src/utils/utils.ts, tests/data/P3035.json, tests/data/Q2112.json, tests/general.ts, tests/simplify_claims.ts
`simplifyClaim` and `simplifySnak` are currently aliases of the same function, which creates complexity and confusion, as a claim has itself a `mainsnak`. By splitting those functions, typing also becomes easier.
Any opinion @EdJoPaTo @mshd?
=> Split simplifyClaim and simplifySnak

src/types/entity.ts
Currently redirects are `string` but it's always of the same type? So we can add types for this to handle them easier.
=> feat: typed redirects on entities

.github/workflows/nodejs.yml
Node.js 20 will be a LTS version from 2023-10-24. Its probably a good idea to also test against it.
=> ci(nodejs): only run on LTS version

docs/sparql_query.md
The original Link [https://meta.wikimedia.org/wiki/User-Agent_policy](https://meta.wikimedia.org/wiki/User-Agent_policy) is now linking to [https://foundation.wikimedia.org/wiki/Policy:User-Agent_policy](https://foundation.wikimedia.org/wiki/Policy:User-Agent_policy).
=> [docs] update link to wikimedia user agent policy
